import { useNavigate } from 'react-router-dom';
import { DEMO_USER } from '../mocks/demoData';
import { getHicQcReport } from '../services/reportService';
import './SignedReportPage.css';

function HicQcSignedReportPage() {
  const navigate = useNavigate();
  const report = getHicQcReport();

  if (!report) {
    return (
      <div className="signed-report-page">
        <div className="report-banner">
          <div className="report-banner-badge">No Report</div>
          <div className="report-banner-text">No HIC QC report has been generated yet.</div>
        </div>
        <div className="report-actions">
          <button className="report-btn-primary" onClick={() => navigate('/apps')}>Back to Apps</button>
        </div>
      </div>
    );
  }

  const { signature, sampleSets, comments, totalSamples, passCount, failCount, reportId, generatedAt } = report;
  const signedDate = new Date(signature.timestamp);
  const generatedDate = new Date(generatedAt);

  return (
    <div className="signed-report-page">
      {/* Banner */}
      <div className="report-banner">
        <div className="report-banner-badge">Certified Copy</div>
        <div className="report-banner-text">
          This document is an electronically signed record generated by the TetraScience Data Platform.
        </div>
      </div>

      {/* Header */}
      <div className="report-header">
        <div className="report-title-row">
          <h1>HIC QC Review &mdash; Signed Report</h1>
          <span className="report-status-badge">Signed</span>
        </div>
        <div className="report-meta-row">
          <span>Report ID: <strong>{reportId}</strong></span>
          <span>Generated: <strong>{generatedDate.toLocaleString()}</strong></span>
        </div>
      </div>

      {/* QC Summary */}
      <div className="report-section">
        <h2>QC Summary</h2>
        <div className="report-grid">
          <div className="report-field">
            <span className="report-label">Sample Sets Reviewed</span>
            <span className="report-value">{sampleSets.length}</span>
          </div>
          <div className="report-field">
            <span className="report-label">Total Samples</span>
            <span className="report-value">{totalSamples}</span>
          </div>
          <div className="report-field">
            <span className="report-label">Passed</span>
            <span className="report-value">{passCount}</span>
          </div>
          <div className="report-field">
            <span className="report-label">Failed / Flagged</span>
            <span className="report-value">{failCount}</span>
          </div>
          <div className="report-field">
            <span className="report-label">App Version</span>
            <span className="report-value">HIC QC App v1.0.0</span>
          </div>
          <div className="report-field">
            <span className="report-label">Dataset Version</span>
            <span className="report-value">{signature.datasetVersion}</span>
          </div>
        </div>
      </div>

      {/* Sample Set Breakdown */}
      <div className="report-section">
        <h2>Sample Set Breakdown</h2>
        <table className="report-table">
          <thead>
            <tr>
              <th>Sample Set</th>
              <th>System</th>
              <th># Samples</th>
              <th>Pass</th>
              <th>Fail</th>
            </tr>
          </thead>
          <tbody>
            {sampleSets.map((ss) => {
              const p = ss.samples.filter((s) => s.qc_status === 'Pass').length;
              return (
                <tr key={ss.sample_set_id}>
                  <td>{ss.sample_set_name}</td>
                  <td>{ss.system_name}</td>
                  <td>{ss.samples.length}</td>
                  <td>{p}</td>
                  <td>{ss.samples.length - p}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Comments */}
      {comments && (
        <div className="report-section">
          <h2>Reviewer Comments</h2>
          <p>{comments}</p>
        </div>
      )}

      {/* Signature Block */}
      <div className="report-section report-signature-block">
        <h2>Electronic Signature</h2>
        <div className="report-grid">
          <div className="report-field">
            <span className="report-label">Signer</span>
            <span className="report-value">{signature.signerName}</span>
          </div>
          <div className="report-field">
            <span className="report-label">User ID</span>
            <span className="report-value">{signature.signerId}</span>
          </div>
          <div className="report-field">
            <span className="report-label">Role</span>
            <span className="report-value">{DEMO_USER.role}</span>
          </div>
          <div className="report-field">
            <span className="report-label">Organization</span>
            <span className="report-value">{DEMO_USER.organization}</span>
          </div>
          <div className="report-field">
            <span className="report-label">Meaning of Signature</span>
            <span className="report-value report-meaning">{signature.meaning}</span>
          </div>
          <div className="report-field">
            <span className="report-label">Authentication Method</span>
            <span className="report-value">{signature.authenticationMethod}</span>
          </div>
          <div className="report-field">
            <span className="report-label">Date &amp; Time</span>
            <span className="report-value">
              {signedDate.toLocaleDateString()} {signedDate.toLocaleTimeString()}
            </span>
          </div>
          <div className="report-field">
            <span className="report-label">Timezone</span>
            <span className="report-value">{signature.timezone}</span>
          </div>
          <div className="report-field full-width">
            <span className="report-label">Signature ID</span>
            <span className="report-value hash">{signature.signatureId}</span>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="report-footer">
        <p>This report was electronically generated and signed via the TetraScience Data Platform.</p>
        <p>Report ID: {reportId} &bull; Dataset Version: {signature.datasetVersion}</p>
      </div>

      {/* Actions (hidden in print) */}
      <div className="report-actions">
        <button className="report-btn-secondary" onClick={() => navigate('/apps/hic-qc/summary')}>
          Back to Summary
        </button>
        <button className="report-btn-secondary" onClick={() => navigate('/audit-trail')}>
          View Audit Trail
        </button>
        <button className="report-btn-primary" onClick={() => window.print()}>
          Print Report
        </button>
      </div>
    </div>
  );
}

export default HicQcSignedReportPage;

